@CourseManagementSystemMicroservice.Basket.Api_HostAddress = http://localhost:5072

GET {{CourseManagementSystemMicroservice.Basket.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

// courseId: 08dd2f78-48b2-47bb-b025-aa525a8a0000
