using CourseManagementSystemMicroservice.Shared;

namespace CourseManagementSystemMicroservice.Basket.Api.Baskets.RemoveDiscountCoupon;

public record RemoveDiscountCouponCommand : IRequestByServiceResult;
